# Generated by Django 4.0.4 on 2022-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
